[tool.poetry]
name = "biopsykitdashboard"
version = "0.1.0"
description = ""
authors = ["Simon Meske <simon.h.meske@fau.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
panel = "^0.14.1"
nilspodlib = "^3.6.0"
biopsykit = "^0.7.1"
pandas = "^1.5.2"
numpy = "^1.23.5"
typing-extensions = "^4.4.0"
packaging = "^21.3"
param = "^1.12.2"
pytz = "^2022.6"
holoviews = "^1.15.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
