applications:
  - url: "home"
    name: Home
    author: simon meske
    owner: 
    category: Main
    description: First Project for a BioPsyKit GUI
    description_long: |-
      First Project for a BioPsyKit GUI
    project: 
    resources:       
      code: https://github.com/awesome-panel/awesome-panel/tree/master/examples/home.py
    servable: 
    tags: 
    thumbnail: "https://github.com/awesome-panel/awesome-panel/raw/master/assets/images/thumbnails/home.png"