name: Test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        pip install poethepoet
        poetry config virtualenvs.in-project true
        poetry install -E mne -E jupyter
    - name: Testing
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        poetry run poe test
